In [6]:
import pandas as pd

In [5]:
from pandas import Series,DataFrame

In [4]:
import numpy as np

In [6]:
df1 = DataFrame({'key':['a','b','b','c','a','c','c'],
               'data1':range(7)})

In [7]:
df2 = DataFrame({'key':['a','b','d'],
                'data2':range(3)})

In [8]:
df1

data1 key
0      0   a
1      1   b
2      2   b
3      3   c
4      4   a
5      5   c
6      6   c

In [9]:
df2

data2 key
0      0   a
1      1   b
2      2   d

In [10]:
pd.merge(df1,df2) #多对一合并，未指定健，将重叠列的列名做为健

data1 key  data2
0      0   a      0
1      4   a      0
2      1   b      1
3      2   b      1

In [12]:
pd.merge(df1,df2,on='key') #指定哪个列当做健

data1 key  data2
0      0   a      0
1      4   a      0
2      1   b      1
3      2   b      1

In [13]:
df3 = DataFrame({'lkey':['a','b','b','c','a','c','c'],
               'data1':range(7)})
df4 = DataFrame({'rkey':['a','b','d'],
                'data2':range(3)})

In [14]:
pd.merge(df3,df4,left_on='lkey',right_on='rkey') #分别指定健

data1 lkey  data2 rkey
0      0    a      0    a
1      4    a      0    a
2      1    b      1    b
3      2    b      1    b

In [18]:
pd.merge(df1,df2,how='outer') #inner取交集,outer取并集,还有left和right

data1 key  data2
0    0.0   a    0.0
1    4.0   a    0.0
2    1.0   b    1.0
3    2.0   b    1.0
4    3.0   c    NaN
5    5.0   c    NaN
6    6.0   c    NaN
7    NaN   d    2.0

In [19]:
left = DataFrame({'key1':['foo','foo','bar'],
                 'key2':['one','two','one'],
                 'lval':[1,2,3]})
right = DataFrame({'key1':['foo','foo','bar','bar'],
                  'key2':['one','one','one','two'],
                  'rval':[4,5,6,7]})

In [23]:
pd.merge(left,right,on=['key1','key2'],how='outer')

key1 key2  lval  rval
0  foo  one   1.0     4
1  foo  one   1.0     5
2  foo  one   2.0     4
3  foo  one   2.0     5
4  bar  two   3.0     7
5  bar  one   NaN     6

In [24]:
pd.merge(left,right,on='key1')

key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    one     2    one     4
3  foo    one     2    one     5
4  bar    two     3    one     6
5  bar    two     3    two     7

In [25]:
pd.merge(left,right,on='key1',suffixes=('_left','_right'))

key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       one     2        one     4
3  foo       one     2        one     5
4  bar       two     3        one     6
5  bar       two     3        two     7

In [7]:
left1 = DataFrame({'key':['a','b','a','a','b','c'],
                          'value':range(6)})
right1 = DataFrame({'group_al':[3.5,7]},index=['a','b'])

In [8]:
pd.merge(left1,right1,left_on='key',right_index=True)
# 索引被用作连接键

key  value  group_al
0   a      0       3.5
2   a      2       3.5
3   a      3       3.5
1   b      1       7.0
4   b      4       7.0

In [9]:
lefth = DataFrame({'key1':['ohio','ohio','ohio','nevada','nevada'],
                  'key2':[2000,2001,2002,2001,2002],
                  'data':np.arange(5)})
righth = DataFrame(np.arange(12).reshape((6,2)),
                  index = [['nevada','nevada','ohio','ohio','ohio','ohio'],
                          [2001,2000,2000,2000,2001,2002]],
                          columns = ['event1','event2'])

In [10]:
lefth

data    key1  key2
0     0    ohio  2000
1     1    ohio  2001
2     2    ohio  2002
3     3  nevada  2001
4     4  nevada  2002

In [11]:
righth

event1  event2
nevada 2001       0       1
       2000       2       3
ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11

In [12]:
pd.merge(lefth,righth,left_on=['key1','key2'],right_index=True)

data    key1  key2  event1  event2
0     0    ohio  2000       4       5
0     0    ohio  2000       6       7
1     1    ohio  2001       8       9
2     2    ohio  2002      10      11
3     3  nevada  2001       0       1

In [13]:
arr = np.arange(12).reshape((4,3))

In [14]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
np.concatenate([arr,arr],axis=1)

array([[ 0,  1,  2,  0,  1,  2],
       [ 3,  4,  5,  3,  4,  5],
       [ 6,  7,  8,  6,  7,  8],
       [ 9, 10, 11,  9, 10, 11]])

In [16]:
np.concatenate([arr,arr])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [17]:
s1 = Series([0,1],index=['a','b'])

In [18]:
s2 = Series([2,3,4],index=['c','d','e'])

In [19]:
s3 = Series([5,6],index=['f','g'])

In [22]:
pd.concat([s1,s2,s3]) # 轴向连接

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [25]:
pd.concat([s1,s2,s3],axis=1) # 轴向连接,如果出入axis=1，变成DataFrame

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [26]:
a = Series([np.nan,2.5,np.nan,3.5,4.5,np.nan])

In [34]:
b = Series(np.arange(len(a),dtype=np.float64),index=['f','e','d','c','b','a'])

In [30]:
a

0    NaN
1    2.5
2    NaN
3    3.5
4    4.5
5    NaN
dtype: float64

In [36]:
b[-1]=np.nan

In [37]:
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    NaN
dtype: float64

In [39]:
np.where(pd.isnull(a),b,a) 
# 合并数据，如果a为空，则b,否则a

array([ 0. ,  2.5,  2. ,  3.5,  4.5,  nan])

In [42]:
b[:-2].combine_first(a[2:])

2    NaN
3    3.5
4    4.5
5    NaN
c    3.0
d    2.0
e    1.0
f    0.0
dtype: float64

In [43]:
df1 = DataFrame({'a':[1,np.nan,5,np.nan],
                'b':[np.nan,2,np.nan,6],
                'c':range(2,18,4)})

In [44]:
df2 = DataFrame({'a':[5,4,np.nan,3,7],
                'b':[np.nan,3,4,6,8]})

In [45]:
df1

a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14

In [46]:
df2

a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0

In [47]:
df1.combine_first(df2) #用df2中的数据为df1的缺失数据打补丁

a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

In [50]:
m=df2.stack() #转化为Series,层次索引

In [52]:
m.unstack() #重排为DataFrame

a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0

In [54]:
data = DataFrame({'k1':['one']*3 + ['two']*4,
                'k2':[1,1,2,3,3,4,4]})

In [55]:
data

k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4

In [57]:
data.duplicated() # 判断各行是否重复

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [58]:
data.drop_duplicates() # 移除重复的行

k1  k2
0  one   1
2  one   2
3  two   3
5  two   4

In [60]:
data.drop_duplicates(['k1'])  # 根据指定的行移除重复行

k1  k2
0  one   1
3  two   3

In [61]:
data1 = Series([1,-999,2,-999,-1000,3])

In [63]:
data1.replace([-999,-1000],np.nan) # 替换值

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [64]:
ages = [20,22,25,27,28,32,43,65,45,33,61,43,37]

In [65]:
bins = [18,25,35,60,100]
cats = pd.cut(ages,bins) 
# 离散化，拆分为‘面元’

In [66]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (25, 35], ..., (35, 60], (25, 35], (60, 100], (35, 60], (35, 60]]
Length: 13
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [68]:
cats.codes #进行标号的label属性

array([0, 0, 0, 1, 1, 1, 2, 3, 2, 1, 3, 2, 2], dtype=int8)

In [74]:
pd.value_counts(cats) #计算各面元中的数据个数

(35, 60]     4
(25, 35]     4
(18, 25]     3
(60, 100]    2
dtype: int64

In [77]:
data2 = np.random.rand(20)

In [78]:
pd.cut(data2,4,precision=2)

[(0.48, 0.71], (0.71, 0.94], (0.018, 0.25], (0.48, 0.71], (0.25, 0.48], ..., (0.48, 0.71], (0.48, 0.71], (0.018, 0.25], (0.25, 0.48], (0.25, 0.48]]
Length: 20
Categories (4, interval[float64]): [(0.018, 0.25] < (0.25, 0.48] < (0.48, 0.71] < (0.71, 0.94]]

In [79]:
data3 = np.random.randn(1000) #正态分布

In [80]:
cats3 = pd.qcut(data3,4) # 按四分位数进行切割

In [81]:
cats3

[(0.711, 3.283], (-0.621, 0.0576], (-2.886, -0.621], (0.0576, 0.711], (0.711, 3.283], ..., (0.0576, 0.711], (-2.886, -0.621], (0.711, 3.283], (-0.621, 0.0576], (0.711, 3.283]]
Length: 1000
Categories (4, interval[float64]): [(-2.886, -0.621] < (-0.621, 0.0576] < (0.0576, 0.711] < (0.711, 3.283]]

In [82]:
data4 = DataFrame(np.random.randn(1000,4))

In [83]:
data4

0         1         2         3
0    0.197019 -1.182682 -0.233849  0.174288
1   -0.892772  0.084325 -0.866351  1.594254
2    0.077352  0.987077 -1.310669 -0.578389
3   -1.038178  0.257422 -0.894842  0.363239
4   -0.381012 -0.268508 -0.724182 -0.907708
5   -0.879134  0.460639  0.251664  0.522855
6    1.132712 -1.496097  1.346012  0.389001
7    1.010940 -0.638748  0.378827  1.017369
8   -0.715801 -1.010597  0.966600  0.654062
9   -0.327580  0.233331  0.678014 -0.384274
10   0.089528 -0.636118  0.485650  0.008647
11   0.058203 -0.204992 -1.805177 -1.242537
12  -1.192035  1.030285 -0.234885 -1.968086
13  -0.200069 -0.541035  0.916613 -0.616715
14  -0.532029  0.137491  0.863763  0.799606
15   1.258518  1.143611 -0.650985  0.789044
16   0.662950 -0.156515  0.618465  0.090719
17   0.932819 -1.249170 -0.682874  0.598458
18   0.151353  0.388342  0.396321 -1.529157
19   1.303257  1.426788 -0.415982 -1.366206
20  -0.324520  0.045385 -1.150804 -0.739361
21  -1.265864  1.387952  1.101436  2.204809
22   0.380097  0.486410 -1.647284 -0.114171
23   0.820846  0.452662  0.305621  1.450325
24   1.007972 -0.846660 -0.742711  1.814272
25   0.515045 -1.071841 -0.521822 -0.612840
26  -0.680547 -0.571955  0.595294 -0.345907
27  -0.153560 -0.613523  1.283602 -0.546955
28  -2.184213  0.497952 -1.316261 -0.031470
29  -0.091192  0.436345  1.439691 -0.192241
..        ...       ...       ...       ...
970  0.412379 -0.107891  0.362612 -0.195365
971 -0.230471  0.985806 -0.679843 -0.773551
972  0.142289  2.989602  0.367093  0.073909
973 -0.750188 -1.048876  1.436691 -0.965912
974  0.186816  0.379161 -0.600299  0.385679
975  1.141625  0.080314  0.671177  0.618133
976  1.847207 -0.337958 -0.084054 -0.707124
977  1.033487  0.129830 -0.704482  0.277448
978  0.153522  2.191314  1.677534  0.014523
979 -2.270277  0.835464 -0.391061  0.631442
980 -0.466012 -0.211860 -0.795557  0.572005
981  1.542365  1.048805 -0.717363  0.152545
982  0.311193  0.184269  0.092196  0.482392
983 -1.526551  0.597213 -0.955937 -0.932744
984  0.611745 -0.829567  0.389802 -0.376429
985 -1.545686  0.659582  2.053561 -0.581517
986 -2.190958 -1.005326 -0.841691  0.429706
987  1.101751  1.336491 -0.012759  0.322297
988  1.256522 -0.312921 -0.029341  0.985740
989 -0.838645 -0.833972 -0.866631 -0.577830
990  0.056825  0.477722  1.109179  0.210582
991  0.728414 -0.716574 -1.094714  0.132249
992 -0.238403 -0.682493 -0.219955 -0.398113
993  0.093671 -2.800590 -0.195700 -2.255046
994  0.254621 -1.536742 -1.402002  0.110398
995  0.131146  0.338222 -0.394018  0.227943
996 -0.733181 -0.351398 -0.599427 -0.398732
997  0.571938  1.417405 -1.276778 -1.615645
998  1.247137  1.169177 -0.267245 -0.350373
999  1.294624 -0.787918  0.373365  0.456657

[1000 rows x 4 columns]

In [84]:
data4.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.022863    -0.002755    -0.019777     0.026800
std       1.038407     0.941358     1.018448     0.998010
min      -3.614027    -2.859493    -3.100763    -2.634261
25%      -0.670540    -0.599945    -0.724954    -0.645427
50%       0.040570    -0.008771    -0.039930     0.010802
75%       0.733467     0.605387     0.685343     0.685538
max       3.592374     3.991572     3.324557     3.098837

In [85]:
col = data4[3]

In [88]:
col[np.abs(col)>3] # 选出某行大于3的数据

677    3.098837
Name: 3, dtype: float64

In [94]:
data4[(np.abs(data4)>3).any(1)] # 选出全部含有绝对值大于3的行

0         1         2         3
45   0.152118  3.991572  1.243638 -1.313674
151  3.288843  0.231142 -0.647720 -0.677447
436  3.211208  0.641420  0.044766  0.733074
552  3.592374  0.010291 -0.256084 -0.834394
677 -0.323062 -0.989548 -0.299904  3.098837
700  0.034439  2.339790 -3.100763 -0.033928
736 -3.230035 -0.106629  0.267348  0.601372
774 -3.614027 -0.289883  2.477893  0.611932
856  3.104168 -2.859493  1.490818 -0.682637
914  0.815255 -0.311387  3.324557  0.034794

In [95]:
data4[np.abs(data4)>3] = np.sign(data4)*3 
# 检测和过滤异常值，将值限制在区间[-3,3]之间
# np.sign返回的是一个由1和-1组成的数组

In [97]:
data4.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.022511    -0.003747    -0.020001     0.026701
std       1.032050     0.937661     1.017132     0.997710
min      -3.000000    -2.859493    -3.000000    -2.634261
25%      -0.670540    -0.599945    -0.724954    -0.645427
50%       0.040570    -0.008771    -0.039930     0.010802
75%       0.733467     0.605387     0.685343     0.685538
max       3.000000     3.000000     3.000000     3.000000

In [98]:
df = DataFrame(np.arange(20).reshape(5,4))

In [99]:
sample = np.random.permutation(5) # 随机排列，产生一个新顺序的整数数组

In [100]:
sample

array([4, 1, 0, 2, 3])

In [101]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [102]:
df.take(sample)

0   1   2   3
4  16  17  18  19
1   4   5   6   7
0   0   1   2   3
2   8   9  10  11
3  12  13  14  15

In [103]:
df.take(np.random.permutation(len(df))[:3]) #随机采样

0   1   2   3
2   8   9  10  11
4  16  17  18  19
0   0   1   2   3

In [104]:
df2 = DataFrame({'key':['b','b','a','c','a','b'],
                'data1':range(6)})

In [105]:
df2

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   b

In [107]:
pd.get_dummies(df2['key'])
# 将分类变量转换为“哑变量矩阵”

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [108]:
values = np.random.rand(10)

In [109]:
values

array([ 0.60588364,  0.73754247,  0.38555921,  0.03242677,  0.36977619,
        0.73998688,  0.34268193,  0.16994256,  0.58796034,  0.82000504])

In [110]:
bins = [0,0.2,0.4,0.6,0.8,1]

In [111]:
pd.get_dummies(pd.cut(values,bins))
# 结合get_dummies和诸如cut之类的离散化函数

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           1           0
1           0           0           0           1           0
2           0           1           0           0           0
3           1           0           0           0           0
4           0           1           0           0           0
5           0           0           0           1           0
6           0           1           0           0           0
7           1           0           0           0           0
8           0           0           1           0           0
9           0           0           0           0           1