In [1]:
import numpy as np

In [9]:
from numpy.random import randn

In [14]:
names = np.array(['bob','joe','will','bob','joe','joe','will'])

In [10]:
data = randn(7,4)

In [11]:
data

array([[  1.18182001e+00,   1.40218739e+00,   8.52342721e-01,
          6.23632089e-01],
       [  1.29801541e+00,  -8.44034065e-01,  -2.18930874e-01,
          1.33162693e-03],
       [ -5.45687406e-01,   5.09350154e-01,   9.61321106e-01,
          3.30150360e-01],
       [ -3.20861317e+00,   5.27304685e-01,  -6.46851804e-01,
          9.98480773e-02],
       [ -4.60236544e-01,  -2.83236214e-01,  -1.31824221e-02,
         -1.55055574e+00],
       [ -7.51741600e-01,  -1.23881962e+00,  -6.75108541e-01,
          2.90214880e-01],
       [  1.68516430e-01,  -4.91216856e-01,  -1.13922778e+00,
         -1.90664638e-01]])

In [13]:
names == 'bob'

True

In [20]:
data[names == 'bob']  # 布尔索引

array([[ 1.18182001,  1.40218739,  0.85234272,  0.62363209],
       [ 0.        ,  0.52730469,  0.        ,  0.09984808]])

In [17]:
data[names == 'bob',:2]

array([[ 1.18182001,  1.40218739],
       [-3.20861317,  0.52730469]])

In [18]:
data[data<0]=0

In [19]:
data

array([[  1.18182001e+00,   1.40218739e+00,   8.52342721e-01,
          6.23632089e-01],
       [  1.29801541e+00,   0.00000000e+00,   0.00000000e+00,
          1.33162693e-03],
       [  0.00000000e+00,   5.09350154e-01,   9.61321106e-01,
          3.30150360e-01],
       [  0.00000000e+00,   5.27304685e-01,   0.00000000e+00,
          9.98480773e-02],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          2.90214880e-01],
       [  1.68516430e-01,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00]])

In [21]:
data[-(names == 'bob')]

TypeError: The numpy boolean negative, the `-` operator, is not supported, use the `~` operator or the logical_not function instead.

In [22]:
arr = np.empty((8,4))

In [38]:
for i in range(8):
    arr[i] = i

In [36]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [39]:
arr[[4,2,3,1]] #花式索引，利用整数数组进行索引

array([[ 4.,  4.,  4.,  4.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [40]:
arr2 = np.arange(32).reshape(8,4)

In [41]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [42]:
arr2.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [43]:
np.dot(arr2,arr2.T)

array([[  14,   38,   62,   86,  110,  134,  158,  182],
       [  38,  126,  214,  302,  390,  478,  566,  654],
       [  62,  214,  366,  518,  670,  822,  974, 1126],
       [  86,  302,  518,  734,  950, 1166, 1382, 1598],
       [ 110,  390,  670,  950, 1230, 1510, 1790, 2070],
       [ 134,  478,  822, 1166, 1510, 1854, 2198, 2542],
       [ 158,  566,  974, 1382, 1790, 2198, 2606, 3014],
       [ 182,  654, 1126, 1598, 2070, 2542, 3014, 3486]])

In [44]:
np.dot(arr2.T,arr2)

array([[2240, 2352, 2464, 2576],
       [2352, 2472, 2592, 2712],
       [2464, 2592, 2720, 2848],
       [2576, 2712, 2848, 2984]])

In [45]:
np.sqrt(arr2)

array([[ 0.        ,  1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974,  2.64575131],
       [ 2.82842712,  3.        ,  3.16227766,  3.31662479],
       [ 3.46410162,  3.60555128,  3.74165739,  3.87298335],
       [ 4.        ,  4.12310563,  4.24264069,  4.35889894],
       [ 4.47213595,  4.58257569,  4.69041576,  4.79583152],
       [ 4.89897949,  5.        ,  5.09901951,  5.19615242],
       [ 5.29150262,  5.38516481,  5.47722558,  5.56776436]])

In [46]:
np.square(arr2)

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225],
       [256, 289, 324, 361],
       [400, 441, 484, 529],
       [576, 625, 676, 729],
       [784, 841, 900, 961]])

In [47]:
points = np.arange(-5,5,0.01)

In [48]:
x,y = meshgrid(points,points)

NameError: name 'meshgrid' is not defined

In [49]:
x,y = np.meshgrid(points,points)

In [50]:
import matplotlib.pyplot as plt

In [51]:
z = np.sqrt(x ** 2, y ** 2)

In [54]:
plt.imshow(z,cmap = plt.cm.gray);plt.colorbar()

In [53]:
plt.title("Image plot of $\sqrt(x^2, y^2)$ for a grid of values")

Text(0.5,1,u'Image plot of $\\sqrt(x^2, y^2)$ for a grid of values')

In [55]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
cond = np.array([True,False,True,True,False])

In [56]:
result = [(x if c else y) for x,y,c in zip(xarr,yarr,cond)]

In [57]:
result

[1.1000000000000001, 2.2000000000000002, 1.3, 1.3999999999999999, 2.5]

In [58]:
result = np.where(xarr,yarr,cond)

In [59]:
result

array([ 2.1,  2.2,  2.3,  2.4,  2.5])

In [60]:
result1 = np.where(cond,xarr,yarr) #将条件逻辑表述为数组运算

In [61]:
result1

array([ 1.1,  2.2,  1.3,  1.4,  2.5])

In [62]:
arr3 = randn(4,4)

In [63]:
arr3

array([[-0.31412588,  0.17005926, -0.28856876,  0.07146089],
       [ 0.75378281,  1.47159278, -1.04533655, -0.8015792 ],
       [-0.76922824, -2.58796771,  0.98640307, -0.23123144],
       [ 0.60366829,  0.95984612,  1.59708237, -1.3296596 ]])

In [64]:
np.where(arr>0,2,-2)

array([[-2, -2, -2, -2],
       [ 2,  2,  2,  2],
       [ 2,  2,  2,  2],
       [ 2,  2,  2,  2],
       [ 2,  2,  2,  2],
       [ 2,  2,  2,  2],
       [ 2,  2,  2,  2],
       [ 2,  2,  2,  2]])

In [65]:
np.where(arr3,3,-3)

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [66]:
np.where(arr3>0,3,-3)

array([[-3,  3, -3,  3],
       [ 3,  3, -3, -3],
       [-3, -3,  3, -3],
       [ 3,  3,  3, -3]])

In [67]:
np.where(arr3>0,4,arr3)

array([[-0.31412588,  4.        , -0.28856876,  4.        ],
       [ 4.        ,  4.        , -1.04533655, -0.8015792 ],
       [-0.76922824, -2.58796771,  4.        , -0.23123144],
       [ 4.        ,  4.        ,  4.        , -1.3296596 ]])

In [68]:
np.mean(arr3)

-0.047112612820556427

In [69]:
np.sum(arr3)

-0.75380180512890282

In [70]:
arr4 = np.range(9).reshape(3,3)

AttributeError: 'module' object has no attribute 'range'

In [72]:
arr5 = np.arange(9).reshape(3,3)

In [73]:
arr5.mean(axis = 1)

array([ 1.,  4.,  7.])

In [74]:
arr5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [75]:
arr5.cumsum(0) # 数学和统计方法

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [76]:
arr5.cumprod(1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

In [77]:
arr5.comprod(0)

AttributeError: 'numpy.ndarray' object has no attribute 'comprod'

In [78]:
arr5.comprod(2)

AttributeError: 'numpy.ndarray' object has no attribute 'comprod'

In [79]:
arr5.comprod(1)

AttributeError: 'numpy.ndarray' object has no attribute 'comprod'

In [80]:
arr5.cumprod(2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [81]:
arr5.cumprod(0)

array([[ 0,  1,  2],
       [ 0,  4, 10],
       [ 0, 28, 80]])

In [82]:
np.max(arr5);np.min(arr5)

0

In [83]:
np.max(arr5)

8

In [84]:
arr6 = randn(10)

In [85]:
arr6

array([ 0.66357008,  0.14827331, -0.92785742, -1.57487622, -0.02776761,
       -1.09961336, -1.48045511,  2.11252415,  0.30823678, -1.43591578])

In [86]:
arr6.sort() #排序

In [87]:
arr6

array([-1.57487622, -1.48045511, -1.43591578, -1.09961336, -0.92785742,
       -0.02776761,  0.14827331,  0.30823678,  0.66357008,  2.11252415])

In [88]:
arr7 = np.array([3,3,4,5,7,7])

In [89]:
np.unique(arr7)

array([3, 4, 5, 7])

In [90]:
np.save('some_array',arr7) #将数组以二进制格式保存到磁盘

In [91]:
np.load('some_array.npy') #读取磁盘上的数组

array([3, 3, 4, 5, 7, 7])

In [95]:
np.savez('array_zip',a = arr6, b = arr7) #将多个数组保存到一个压缩文件中

In [96]:
arch = np.load('array_zip.npz')

In [97]:
arch['a']

array([-1.57487622, -1.48045511, -1.43591578, -1.09961336, -0.92785742,
       -0.02776761,  0.14827331,  0.30823678,  0.66357008,  2.11252415])

In [101]:
x = np.arange(1,7).reshape(2,3)

In [102]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
y = np.arange(1,7).reshape(3,2)

In [104]:
x.dot(y)

array([[22, 28],
       [49, 64]])

In [105]:
%timeit np.random.normal(size=1000000)

1 loop, best of 3: 160 ms per loop


In [107]:
nsteps = 1000
draws = np.random.randint(0,2,size=nsteps)
steps = np.where(draws>0,1,-1)
walk = steps.cumsum()

In [108]:
walk.max()

28

In [110]:
sdata = {'ohio':35000,'texas':71000,'oregon':16000,'utah':5000}